/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasikesehatan;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Frame3 extends javax.swing.JFrame {
    String temp="";
    Double tin ,bt ,h1;


    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        query1 = java.beans.Beans.isDesignTime() ? null : ((javax.persistence.EntityManager)null).createQuery("");
        ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnhitung = new javax.swing.JButton();
        tinggi = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        berat = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/3181-3767-thickbox.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(ideal);
        ideal.setBounds(280, 330, 50, 30);

        jLabel7.setBackground(new java.awt.Color(51, 255, 51));
        jLabel7.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 330, 30, 30);

        panel1.setBackground(new java.awt.Color(255, 255, 0));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        panel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("TS'24 HOSPITAL");
        panel1.add(jLabel9);
        jLabel9.setBounds(40, 40, 140, 20);

        jLabel8.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("AYO CEK IDEALMU");
        panel1.add(jLabel8);
        jLabel8.setBounds(120, 10, 300, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Nama");
        panel1.add(jLabel3);
        jLabel3.setBounds(40, 80, 110, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Tinggi Badan");
        panel1.add(jLabel4);
        jLabel4.setBounds(40, 130, 140, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Berat Badan");
        panel1.add(jLabel5);
        jLabel5.setBounds(40, 180, 130, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Jenis Kelamin");
        panel1.add(jLabel1);
        jLabel1.setBounds(40, 240, 110, 20);

        jLabel6.setBackground(new java.awt.Color(51, 255, 51));
        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Berat badan ideal Anda adalah ");
        panel1.add(jLabel6);
        jLabel6.setBounds(30, 340, 260, 30);

        btnhitung.setBackground(new java.awt.Color(255, 102, 102));
        btnhitung.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        panel1.add(btnhitung);
        btnhitung.setBounds(100, 290, 100, 30);

        tinggi.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        panel1.add(tinggi);
        tinggi.setBounds(160, 130, 240, 30);

        nama.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        panel1.add(nama);
        nama.setBounds(160, 80, 240, 30);

        berat.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        panel1.add(berat);
        berat.setBounds(160, 180, 240, 30);

        hasil.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        panel1.add(hasil);
        hasil.setBounds(10, 380, 420, 30);

        saran.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        panel1.add(saran);
        saran.setBounds(10, 420, 420, 30);

        btnreset.setBackground(new java.awt.Color(102, 255, 255));
        btnreset.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        panel1.add(btnreset);
        btnreset.setBounds(220, 290, 110, 30);

        laki.setBackground(new java.awt.Color(255, 0, 102));
        buttonGroup1.add(laki);
        laki.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        laki.setText("Laki - Laki");
        panel1.add(laki);
        laki.setBounds(290, 240, 100, 23);

        perempuan.setBackground(new java.awt.Color(255, 0, 102));
        buttonGroup1.add(perempuan);
        perempuan.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        perempuan.setText("Perempuan");
        panel1.add(perempuan);
        perempuan.setBounds(160, 240, 110, 23);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 440, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        if(berat.getText().equals("")||tinggi.getText().equals("")||nama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak isian Belum diisi, maka harus diisi");

        }else if (perempuan.isSelected()||laki.isSelected())
        try{
            Proses();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
        }
        else {
            JOptionPane.showMessageDialog(null,  "Jenis Kelamin silahkan diisi");
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
            nama.setText("");
            tinggi.setText("");
            berat.setText("");
            buttonGroup1.clearSelection();
            ideal.setText("");
            saran.setText("");
            hasil.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnreset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton perempuan;
    private javax.persistence.Query query1;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
         tin = Double.valueOf(tinggi.getText());
         bt = Double.valueOf(berat.getText());
        
        if(perempuan.isSelected()) {
            h1 = (tin - 110) * 1;
        } else if (laki.isSelected()) {
            h1 = (tin - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        if(h1 < bt) {
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText() + " , Sepertinya Anda Overweight :(");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol yaa");
        
        } else if (h1>bt) {
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText() + " , Sepertinya adan underweight :(");
            saran.setText("Banyaklah berolahraga dan makan makanan berkarbohidrat tinggi yaa");
     
        }else {
            ideal.setText(temp);
            hasil.setText("Haloo " + nama.getText() + " Berat Anda sudah ideal :)");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
            
        }}

   
}
